services:
  # --------------------------------------------
  java-app-cra: 
    build:
      context: ./optitalent
      dockerfile: Dockerfile
    container_name: java-app-cra
    depends_on:
      postgres-cra:
        condition: service_healthy
    ports:
      - "8009:8080"
    networks:
      - app-network-cra

  # --------------------------------------------
  postgres-cra:
    image: postgres:15
    container_name: postgres-cra
    volumes:
      - ./PostgreSQL/pg_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: optitalent
      POSTGRES_USER: optitalent
      POSTGRES_PASSWORD: 123456789
    ports:
      - "5432:5432"
    networks:
      - app-network-cra
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U optitalent" ]
      interval: 30s
      timeout: 10s
      retries: 5

  # --------------------------------------------
  adminer-cra:
    image: adminer
    container_name: adminer-cra
    depends_on:
      - postgres-cra
    ports:
      - "8010:8080"
    networks:
      - app-network-cra

# --------------------------------------------
networks:
  app-network-cra:
    driver: bridge
    name: app-network-cra
